// Auto-generated by ono-auto-router
import type { RouteObject } from 'react-router'
import Pages from './../pages/index.tsx'
import PagesReceive from './../pages/receive.tsx'
import PagesSend from './../pages/send.tsx'
import PagesSettings from './../pages/settings.tsx'
import PagesRoot from './../pages/__root__.tsx'

type PageConfig = Partial<
  Omit<RouteObject, 'Component' | 'element' | 'children'> & {
    type?: 'single' | 'wrap'
  }
>

export const defineConfig = (config: PageConfig) => config

export const routes: RouteObject[] = [
  {
    path: '/',
    element: <PagesRoot />,
    children: [
      {
        path: '/',
        element: <Pages />,
        index: true
      },
      {
        path: '/send',
        children: [
          {
            path: '',
            index: true,
            element: <PagesSend />
          }
        ]
      },
      {
        path: '/receive',
        children: [
          {
            path: '',
            index: true,
            element: <PagesReceive />
          }
        ]
      },
      {
        path: '/settings',
        children: [
          {
            path: '',
            index: true,
            element: <PagesSettings />
          }
        ]
      }
    ]
  }
]
