// Auto-generated by ono-auto-router
import type { RouteObject } from 'react-router'
import Pages from './../pages/index.tsx'
import PagesRoot_1 from './../pages/__root__.tsx'
import PagesSettings from './../pages/settings/index.tsx'
import PagesTransfer from './../pages/transfer/index.tsx'

type PageConfig = Partial<
  Omit<RouteObject, 'Component' | 'element' | 'children'> & {
    type?: 'single' | 'wrap'
  }
>

export const defineConfig = (config: PageConfig) => config

export const routes: RouteObject[] = [
  {
    path: '/',
    element: <PagesRoot_1 />,
    children: [
      {
        path: '/',
        element: <Pages />,
        index: true
      },
      {
        path: '/settings',
        children: [
          {
            path: '',
            index: true,
            element: <PagesSettings />
          }
        ]
      },
      {
        path: '/transfer',
        children: [
          {
            path: '',
            index: true,
            element: <PagesTransfer />
          }
        ]
      }
    ]
  }
]
